### ISSUE TITLE
Parameter to keep X oldest releases and delete the rest

### ISSUE THREAD

**Issue by thadguidry** [meeDamian/github-release#14]
We create a bunch of releases (temp dev versions) of our open source software, OpenRefine.
See for example: https://github.com/OpenRefine/OpenRefine-nightly-releases/releases

It would be nice to use your action with a new parameter where I specify `keep:3` to keep the 3 latest releases and it then deletes all the older releases.

Any chance you could add that option?
Or a brand new action called `delete-older-releases` ?
I looked around and didn't find something that would work.  But pointers welcome.

**Comment by meeDamian** [comment]
Hey, thank you for suggestion!

I think adding this here would extend a bit too far outside responsibilities of this action, and I don't really have a time to create a new one.  That being said, something like this can be a good start if you'd like to create it yourself:

```sh
#!/usr/bin/env sh

set -e

# Needed deps: curl jq

TOKEN="$INPUT_TOKEN"
KEEP="${INPUT_KEEP:-5}"
REPO=${GITHUB_REPOSITORY:-bitcoin/bitcoin}


if [ -z "$TOKEN" ]; then
	>&2 echo "Github Token required"
	exit 1
fi

url="https://api.github.com/repos/$REPO/releases"
headers="$(mktemp -d)"

api() {
	url="$1"; method="${2:-GET}"
	curl -sS -D "$headers/$method" -H "Authorization: token $TOKEN"  -X "$method"  "$url"
}

ids=
while [ -n "$url" ] && ids="$(api "$url" | jq -r '.[].id')${ids:+\n$ids}"; do
	url="$(sed -nE 's|link: <(.*)>; rel="next".*|\1|p' "$headers/GET")"
done

i=0
for id in $(echo "$ids" | sort -rn); do
	if [ "$i" -lt "$KEEP" ]; then
		i=$((i+1))
		echo "keep   $id"
		continue
	fi

	echo "delete $id"
	api "$url/$id" DELETE
done
```

Hope that helps :).

**Comment by meeDamian** [comment]
And if you don't care about pagination, or draft releases, sth like this should work too:

```sh
url="https://api.github.com/repos/OpenRefine/OpenRefine-nightly-releases/releases"
curl -sS "$url" \
	| jq  -r '.[].id' \
	| sort -n \
	| head -n-3 \
	| xargs -I%  curl -sS -X DELETE -H "Authorization: token $TOKEN" "$url/%"
```

**Comment by thadguidry** [comment]
@meeDamian Thanks anyways.  Good news is that we were able to convince another author (Reddy Prasad) to make a fantastic new GitHub Action for the entire community!
- It deletes Older Releases
- Optionally can delete Tags and Files as well

https://github.com/dev-drprasad/delete-older-releases

It's quite awesome and we use it now in OpenRefine's CI/CD!
