### ISSUE TITLE
Allow a environment variable usage in filenames

### ISSUE THREAD

**Issue by cilerler** [meeDamian/github-release#4]
I would like to be able to use `buildNumber` environment variable in my asset name

```
        files: >
          artifacts-${buildNumber}:./artifacts/ArtifactStagingDirectory
```

or alternatively, allow using TAG _(which will be same as buildNumber in my case)_

```
        files: >
          artifacts-${TAG}:./artifacts/ArtifactStagingDirectory
```

**Comment by meeDamian** [comment]
Since I can't control how GH actions inputs are processed, I can only process them the same way #3 happens - by using an ex: `RELEASE_FILES` env variable.

What do you think?

**Comment by cilerler** [comment]
I didn't see your message on this, sorry.
Let me give you more clear inside on this since I believe we are on different pages.
I want to be able to add a suffix to files.

so;
if input is
```
        files: >
          ./artifacts/ArtifactStagingDirectory
```
it should use the actual filenames
```
        files: >
         artifacts: ./artifacts/ArtifactStagingDirectory
```
Should use `artifacts` as the name.
However, if I set something like the RELEASE_FILES_SUFFIX environment variable, it should add those to the name I already set.
```
        files: >
         artifacts-${RELEASE_FILES_SUFFIX}: ./artifacts/ArtifactStagingDirectory
```

Please let me know if you need further detail

**Comment by meeDamian** [comment]
I've released a new version (`v1.0.1`) that exposes `RELEASE_FILES` variable, so you can just set it to whatever is needed.

**Comment by cilerler** [comment]
let me check, and I will get back to you

**Comment by cilerler** [comment]
ok tested all, and first two issues are working like a charm, however, couldn't make this one to work, due to the multiline syntax :(

Can you give me an example of how to put multiple-lines into a variable? Remember Windows guy here :)

Thank you very much!

```
        files: >
          artifacts-${RELEASE_TAG}:./artifacts/ArtifactStagingDirectory
          ./artifacts/NuGetPackages/*.nupkg
```

**Comment by meeDamian** [comment]
It's a space-separated list ;).  Not new-line-separated one.

`>` symbol in yaml does just that.  Ignores all newlines that follow.  You can play with it here: https://yaml-multiline.info/

**Comment by cilerler** [comment]
😂 it worked perfectly, thanks!

![bitmoji](https://render.bitstrips.com/v2/cpanel/c01f75cb-46fb-48c6-b217-e765d364b6c9-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)
