### ISSUE TITLE
Use workflow name as default release name

### ISSUE THREAD

**Issue by cilerler** [meeDamian/github-release#5]
Instead of using the **Branch** name, using the **Workflow** name as default name would be more useful

```sh
RELEASE_NAME="${INPUT_NAME}"
if [ -z "${RELEASE_NAME}" ]; then
  RELEASE_NAME="${GITHUB_WORKFLOW}"
fi
```

```sh
  --argjson name              "$(toJsonOrNull "${RELEASE_NAME}")"       \
```

**Comment by meeDamian** [comment]
Branch name leakage was a bug, that I've fixed here: https://github.com/meeDamian/github-release/commit/635d8d8db698f7fb13b57e4eb85db6b4ff809e01 .

Can't imagine scenarios where naming releases after workflow file would make sense - care to elaborate?

**Comment by cilerler** [comment]
If you are producing multiple libraries from a repo, it is handy.  Check this out https://github.com/cilerler/ruya/releases (by the way, generated those with the way I suggested.

**Comment by meeDamian** [comment]
Alright, gotcha!

I think doing it by default might be confusing as I would guess it's not a very common case, would exposing a this option as a corresponding var env help?

**Comment by cilerler** [comment]
Definitely! Be able to use ENVVAR would solve most of the problems I reported.

![bitmoji](https://render.bitstrips.com/v2/cpanel/ef534e16-69f9-4568-92e4-554ab1d99d40-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)
