### ISSUE TITLE
Add support for regular zip

### ISSUE THREAD

**Issue by cilerler** [meeDamian/github-release#8]
As you may see in attachment, GitHub provides both formats `zip` and `tar.gz`.
Please add support for regular `zip`

![image](https://user-images.githubusercontent.com/385958/66265635-e069c300-e7e7-11e9-964a-8ea1565a5fd8.png)

**Comment by meeDamian** [comment]
You mean:

1. Instead of `.tar.gz`,
1. Duplicate all files to be compressed with both, or
1. Specify on per-file basis

?

**Comment by cilerler** [comment]
Well, it depends, and I believe it should be optional.

1. For the consistency purpose, the app should generate `.tar.gz` and not `.tgz`
2. Not everybody may want to have both versions of the artifact, so it can be set through a flag, which has options of `zip`, `.tar.gz` and `both`
3. I believe it would be overkill

**Comment by meeDamian** [comment]
The thing is that `.zip` is only popular on Windows AFAIK, while `.tar.gz` is the default on all linuxes, and MacOS.

From what I remember, the only usage of `.zip` I've seen here is for windows-specific resources, ex: https://github.com/lightningnetwork/lnd/releases/tag/v0.7.1-beta (scroll all the way down).

Anyway, I need to think about it more, and in the meantime you can zip them beforehand, and then use `gzip: false` :).

**Comment by cilerler** [comment]
I hear you, and you are right about `.zip`. But please remember that `.tar.gz` is default on Linux, where `.zip` is default on Windows. And there is excellent reasoning behind the scene why GitHub provides both of them. Your GitHub Action is the number 1 for releasing at this point with all the features it has, let's not give it away because you are not a Windows user ;-)  I hope this will convince you, looking forward to seeing it.

**Comment by meeDamian** [comment]
Please use https://github.com/actions/upload-release-asset now instead.
