### ISSUE TITLE
Container action is only supported on Linux

### ISSUE THREAD

**Issue by cilerler** [meeDamian/github-release#9]
hit the brick wall, getting the error below

```
##[error]Container action is only supported on Linux
```
You may use https://github.com/cilerler/test-github-actions2 as a scratchpad.

![image](https://user-images.githubusercontent.com/385958/66281610-1c556480-e88a-11e9-8b9f-65b09fa335e0.png)

**Comment by meeDamian** [comment]
Pretty sure [this] is your problem.  My guess would be that Github's [container actions] are currently not supported on Windows.

A workaround (apart from not using Windows as base image) would be to, [upload artifacts] in this job, and then have a dependent linux-based job that [downloads them], and uploads them to GH releases.

[this]: https://github.com/cilerler/test-github-actions2/blob/master/.github/workflows/Burcin.Templates.CSharp.yml#L21
[container actions]: https://help.github.com/en/articles/creating-a-docker-container-action
[upload artifacts]: https://github.com/actions/upload-artifact
[downloads them]: https://github.com/actions/download-artifact
